// keymap_layers.c generator — moved from FirmwarePanel.jsx unchanged.

export function buildKeymapLayersCCode(allKeymaps, layerCount) {
  const rows = 10;
  const cols = 6;
  const layers = [];
  for (let l = 0; l < layerCount; l++) {
    const layer = allKeymaps[l] ?? Array.from({ length: rows }, () => Array(cols).fill(0));
    const rowLines = layer.map(row => {
      const padded = Array.from({ length: cols }, (_, c) => row[c] ?? 0);
      const cells = padded.map(k => `0x${k.toString(16).padStart(4, '0').toUpperCase()}`);
      return `        { ${cells.join(', ')} }`;
    });
    layers.push(`    [${l}] = {\n${rowLines.join(',\n')}\n    }`);
  }
  return [
    '// Keymap layers — generated by Iris Key Editor.',
    '// Re-generate in Firmware → Write Keymap Source, then click Save to file.',
    'const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {',
    layers.join(',\n'),
    '};',
    '',
  ].join('\n');
}
