// per_key_colors.c generator — moved from LightingPanel.jsx unchanged.

export const NUM_LEDS = 68;

export function hsvToRgb255(h, s, v) {
  const hDeg = (h / 255) * 360;
  const sN = s / 255, vN = v / 255;
  const c = vN * sN;
  const x = c * (1 - Math.abs((hDeg / 60) % 2 - 1));
  const m = vN - c;
  let r, g, b;
  if      (hDeg < 60)  { r = c; g = x; b = 0; }
  else if (hDeg < 120) { r = x; g = c; b = 0; }
  else if (hDeg < 180) { r = 0; g = c; b = x; }
  else if (hDeg < 240) { r = 0; g = x; b = c; }
  else if (hDeg < 300) { r = x; g = 0; b = c; }
  else                  { r = c; g = 0; b = x; }
  return [Math.round((r + m) * 255), Math.round((g + m) * 255), Math.round((b + m) * 255)];
}

export function buildPerKeyColorsCCode(perKeyColors, layerCount) {
  const toHex2 = n => n.toString(16).padStart(2, '0').toUpperCase();

  // Collect every LED index that has a color on any layer
  const usedLeds = new Set();
  for (let layer = 0; layer < layerCount; layer++) {
    const cols = perKeyColors[layer];
    for (let led = 0; led < NUM_LEDS; led++) {
      if (cols[led]) usedLeds.add(led);
    }
  }

  if (usedLeds.size === 0) {
    return [
      '// Per-key colors — generated by Iris Key Editor.',
      '// Included by keymap.c; call apply_per_key_colors(layer) from',
      '// rgb_matrix_indicators_advanced_user.',
      'static void apply_per_key_colors(uint8_t layer) {',
      '    (void)layer;',
      '}',
    ].join('\n');
  }

  // Clear all used LEDs first — prevents bleed when switching to a layer with no colors.
  // In Direct mode QMK's frame buffer persists; without an explicit clear the previous
  // layer's colors stay lit on LEDs the new layer doesn't touch.
  const clearLines = [...usedLeds].sort((a, b) => a - b)
    .map(led => `    rgb_matrix_set_color(${led.toString().padStart(2)}, 0, 0, 0);`);

  const cases = [];
  for (let layer = 0; layer < layerCount; layer++) {
    const cols = perKeyColors[layer];
    const lines = [];
    for (let led = 0; led < NUM_LEDS; led++) {
      if (!cols[led]) continue;
      const [r, g, b] = hsvToRgb255(...cols[led]);
      lines.push(`            rgb_matrix_set_color(${led.toString().padStart(2)}, 0x${toHex2(r)}, 0x${toHex2(g)}, 0x${toHex2(b)});`);
    }
    if (lines.length) {
      cases.push(`        case ${layer}:\n${lines.join('\n')}\n            break;`);
    }
  }

  const body = [
    clearLines.join('\n'),
    `    switch (layer) {\n${cases.join('\n')}\n        default: break;\n    }`,
  ].join('\n');

  return [
    '// Per-key colors — generated by Iris Key Editor.',
    '// Included by keymap.c; call apply_per_key_colors(layer) from',
    '// rgb_matrix_indicators_advanced_user.',
    'static void apply_per_key_colors(uint8_t layer) {',
    body,
    '}',
  ].join('\n');
}
