// scroll_text.c generator — moved from LightingPanel.jsx unchanged.

import { hsvToRgb255 } from './perKeyColors';

// 3-wide × 4-tall pixel font. Each char is [row0,row1,row2,row3], 3-bit mask:
//   bit2 = left col, bit1 = mid col, bit0 = right col
const SCROLL_FONT = {
  ' ': [0,0,0,0],
  'A': [2,5,7,5], 'B': [6,7,6,7], 'C': [3,4,4,3], 'D': [6,5,5,6],
  'E': [7,6,4,7], 'F': [7,6,4,4], 'G': [3,4,5,3], 'H': [5,7,5,5],
  'I': [7,2,2,7], 'J': [1,1,5,2], 'K': [5,6,6,5], 'L': [4,4,4,7],
  'M': [7,2,5,5], 'N': [5,6,3,5], 'O': [2,5,5,2], 'P': [6,5,6,4],
  'Q': [2,5,5,3], 'R': [6,5,6,5], 'S': [3,6,1,6], 'T': [7,2,2,2],
  'U': [5,5,5,2], 'V': [5,5,2,2], 'W': [5,5,7,2], 'X': [5,2,2,5],
  'Y': [5,2,2,2], 'Z': [7,1,4,7],
  '0': [2,5,5,2], '1': [2,6,2,7], '2': [6,1,2,7], '3': [6,3,1,6],
  '4': [5,7,1,1], '5': [7,6,1,6], '6': [3,4,6,2], '7': [7,1,2,2],
  '8': [2,5,2,5], '9': [5,7,1,6],
  '!': [2,2,0,2], '?': [2,1,2,0], '-': [0,7,0,0], '.': [0,0,0,2],
  ':': [0,2,0,2],
};

// 12-wide × 4-tall grid of LED indices: left half cols 0-5, right half cols 5-0 (mirrored)
const LED_GRID_12X4 = [
  [ 0,  2,  3,  5,  6,  8, 42, 40, 39, 37, 36, 34],
  [14, 13, 12, 11, 10,  9, 43, 44, 45, 46, 47, 48],
  [15, 16, 17, 18, 19, 20, 54, 53, 52, 51, 50, 49],
  [28, 26, 25, 23, 22, 21, 55, 56, 57, 59, 60, 62],
];

// Build a pixel tape from text. Returns tape[4][N] where each cell is 0 or 1.
// Layout: 12-col blank lead-in, then chars (3px wide + 1px gap each).
export function buildScrollTape(text) {
  const CHAR_W = 3, GAP = 1, LEAD = 12;
  const tape = [[], [], [], []];
  for (let i = 0; i < LEAD; i++) for (let r = 0; r < 4; r++) tape[r].push(0);
  for (const ch of text.toUpperCase()) {
    const def = SCROLL_FONT[ch] ?? SCROLL_FONT[' '];
    for (let c = 0; c < CHAR_W; c++)
      for (let r = 0; r < 4; r++) tape[r].push((def[r] >> (CHAR_W - 1 - c)) & 1);
    for (let i = 0; i < GAP; i++) for (let r = 0; r < 4; r++) tape[r].push(0);
  }
  return tape;
}

export function buildScrollCCode(text, layer, speedMs, fgHsv, bgHsv) {
  if (!text.trim()) return [
    '// Scroll text — generated by Iris Key Editor.',
    '// Included by keymap.c; call apply_scroll_text(layer) from',
    '// rgb_matrix_indicators_advanced_user.',
    '// Re-generate in Lighting → Scroll Text tab, then click Save to file.',
    '',
    'static void apply_scroll_text(uint8_t layer) {}',
  ].join('\n');
  const tape = buildScrollTape(text);
  const W    = tape[0].length;
  const [fr, fg, fb] = hsvToRgb255(...fgHsv);
  const [br, bg, bb] = bgHsv ? hsvToRgb255(...bgHsv) : [0, 0, 0];
  const toH  = n => `0x${n.toString(16).padStart(2, '00').toUpperCase()}`;

  const fmtRow = row => {
    const chunks = [];
    for (let i = 0; i < row.length; i += 16)
      chunks.push('        ' + row.slice(i, i + 16).join(', '));
    return chunks.join(',\n');
  };
  const tapeC  = tape.map((row, r) => `    /* row ${r} */ {\n${fmtRow(row)}\n    }`).join(',\n');
  const gridC  = LED_GRID_12X4.map(row => `    {${row.map(v => String(v).padStart(3)).join(',')}}`).join(',\n');

  return [
    '// Scroll text — generated by Iris Key Editor.',
    '// Included by keymap.c; call apply_scroll_text(layer) from',
    '// rgb_matrix_indicators_advanced_user.',
    '// Re-generate in Lighting → Scroll Text tab, then click Save to file.',
    '',
    `#define SCROLL_LAYER  ${layer}`,
    `#define SCROLL_SPEED  ${speedMs}`,
    `#define SCROLL_FG_R   ${toH(fr)}`,
    `#define SCROLL_FG_G   ${toH(fg)}`,
    `#define SCROLL_FG_B   ${toH(fb)}`,
    `#define SCROLL_BG_R   ${toH(br)}`,
    `#define SCROLL_BG_G   ${toH(bg)}`,
    `#define SCROLL_BG_B   ${toH(bb)}`,
    `#define TAPE_WIDTH    ${W}`,
    '',
    'static const uint8_t IRIS_GRID[4][12] = {',
    gridC,
    '};',
    '',
    'static const uint8_t SCROLL_TAPE[4][TAPE_WIDTH] = {',
    tapeC,
    '};',
    '',
    'static uint32_t scroll_timer  = 0;',
    'static uint16_t scroll_offset = 0;',
    '',
    'static void apply_scroll_text(uint8_t layer) {',
    '    if (layer != SCROLL_LAYER) return;',
    '    if (timer_elapsed32(scroll_timer) >= SCROLL_SPEED) {',
    '        scroll_timer = timer_read32();',
    '        if (++scroll_offset >= TAPE_WIDTH) scroll_offset = 0;',
    '    }',
    '    for (uint8_t r = 0; r < 4; r++) {',
    '        for (uint8_t c = 0; c < 12; c++) {',
    '            uint8_t  led = IRIS_GRID[r][c];',
    '            uint16_t tc  = (scroll_offset + c) % TAPE_WIDTH;',
    '            bool     lit = SCROLL_TAPE[r][tc];',
    '            rgb_matrix_set_color(led,',
    '                lit ? SCROLL_FG_R : SCROLL_BG_R,',
    '                lit ? SCROLL_FG_G : SCROLL_BG_G,',
    '                lit ? SCROLL_FG_B : SCROLL_BG_B);',
    '        }',
    '    }',
    '}',
  ].join('\n');
}
