// tap_dance_keys.c generator — moved from TapDanceKeyPanel.jsx unchanged.

import { keycodeToC } from '../keycodeToC';

export const TD_FIELDS = [
  { key: 'on_tap',        label: 'On Tap' },
  { key: 'on_hold',       label: 'On Hold' },
  { key: 'on_double_tap', label: 'Double Tap' },
  { key: 'on_tap_hold',   label: 'Tap + Hold' },
];

function keyIdToEnum(id) {
  return `TD_${id.replace(/-/g, '_').toUpperCase()}`;
}

// register_code16/unregister_code16 silently no-op on QMK layer-switch keycodes
// (process_record_quantum handles those, not the HID code path) — emit the
// equivalent layer_* call instead. release === null means nothing to undo.
function layerKeycodeAction(code) {
  if ((code & 0xFFF0) === 0x5220) {
    const n = code & 0xF;
    return { press: `layer_on(${n});`, release: `layer_off(${n});` };
  }
  if ((code & 0xFFF0) === 0x5230) {
    const n = code & 0xF;
    return { press: `layer_invert(${n});`, release: null };
  }
  if (code >= 0x5200 && code <= 0x521F) {
    const n = code & 0x1F;
    return { press: `layer_move(${n});`, release: null };
  }
  return null;
}

export function buildTapDanceCCode(tapDanceKeys) {
  // Collect unique key IDs across all layers that have any config
  const keyIds = new Set();
  Object.values(tapDanceKeys).forEach(layerObj => {
    Object.entries(layerObj ?? {}).forEach(([keyId, e]) => {
      if (TD_FIELDS.some(f => (e[f.key] ?? 0) !== 0)) keyIds.add(keyId);
    });
  });

  if (keyIds.size === 0) return '// No tap dance keys configured.';

  const stateMap = ['TD_SINGLE_TAP', 'TD_SINGLE_HOLD', 'TD_DOUBLE_TAP', 'TD_DOUBLE_HOLD'];
  const enumValues = [...keyIds].map(id => `    ${keyIdToEnum(id)}`).join(',\n');

  const callbacks = [...keyIds].map(id => {
    const enumId = keyIdToEnum(id);
    const fnBase = enumId.toLowerCase();
    const varName = `${fnBase}_state`;

    // Per-layer cases
    const layerCases = Object.entries(tapDanceKeys)
      .filter(([, layerObj]) => {
        const e = layerObj?.[id];
        return e && TD_FIELDS.some(f => (e[f.key] ?? 0) !== 0);
      })
      .map(([layerIdx, layerObj]) => {
        const e = layerObj[id];
        const pressLines = TD_FIELDS
          .map(({ key }, i) => {
            const code = e[key] ?? 0;
            if (code === 0) return null;
            const layerAction = layerKeycodeAction(code);
            const stmt = layerAction ? layerAction.press : `register_code16(${keycodeToC(code)});`;
            return `                case ${stateMap[i]}: ${stmt} break;`;
          })
          .filter(Boolean).join('\n');
        return `        case ${layerIdx}:\n            switch (${varName}.state) {\n${pressLines}\n                default: break;\n            }\n            break;`;
      }).join('\n');

    const unregCases = Object.entries(tapDanceKeys)
      .filter(([, layerObj]) => {
        const e = layerObj?.[id];
        return e && TD_FIELDS.some(f => (e[f.key] ?? 0) !== 0);
      })
      .map(([layerIdx, layerObj]) => {
        const e = layerObj[id];
        const releaseLines = TD_FIELDS
          .map(({ key }, i) => {
            const code = e[key] ?? 0;
            if (code === 0) return null;
            const layerAction = layerKeycodeAction(code);
            if (layerAction) {
              return layerAction.release
                ? `                case ${stateMap[i]}: ${layerAction.release} break;`
                : null;
            }
            return `                case ${stateMap[i]}: unregister_code16(${keycodeToC(code)}); break;`;
          })
          .filter(Boolean).join('\n');
        return `        case ${layerIdx}:\n            switch (${varName}.state) {\n${releaseLines}\n                default: break;\n            }\n            break;`;
      }).join('\n');

    return `static td_tap_t ${varName} = {0};

void ${fnBase}_finished(tap_dance_state_t *state, void *user_data) {
    ${varName}.state = cur_dance(state);
    uint8_t layer = get_highest_layer(layer_state);
    switch (layer) {
${layerCases}
        default: break;
    }
}

void ${fnBase}_reset(tap_dance_state_t *state, void *user_data) {
    uint8_t layer = get_highest_layer(layer_state);
    switch (layer) {
${unregCases}
        default: break;
    }
    ${varName}.state = TD_NONE;
}`;
  }).join('\n\n');

  const actionsTable = [...keyIds]
    .map(id => {
      const enumId = keyIdToEnum(id);
      return `    [${enumId}] = ACTION_TAP_DANCE_FN_ADVANCED(NULL, ${enumId.toLowerCase()}_finished, ${enumId.toLowerCase()}_reset)`;
    }).join(',\n');

  return `// Tap Dance keys — generated by Iris Key Editor.
// Included by keymap.c after td_state_t / td_tap_t / cur_dance are defined.
// Use TD(ENUM_NAME) in keymap layers. TAP_DANCE_ENABLE = yes in rules.mk.

enum {
${enumValues}
};

${callbacks}

tap_dance_action_t tap_dance_actions[] = {
${actionsTable}
};`;
}
