import React, { useState } from 'react';
import { decodeQuantum, KEYCODE_MAP, HALVES } from '../keyboardLayout';
import KeyPicker from './KeyPicker';
import './TapDanceKeyPanel.css';

const EMPTY_ENTRY = { on_tap: 0, on_hold: 0, on_double_tap: 0, on_tap_hold: 0, tapping_term_ms: 0 };

const FIELDS = [
  { key: 'on_tap',        label: 'On Tap' },
  { key: 'on_hold',       label: 'On Hold' },
  { key: 'on_double_tap', label: 'Double Tap' },
  { key: 'on_tap_hold',   label: 'Tap + Hold' },
];

// Convert QMK 16-bit keycode to C macro string
function keycodeToC(code) {
  if (!code || code === 0) return 'KC_NO';
  if (code === 0x0001) return 'KC_TRNS';
  if (code <= 0x00FF) {
    const name = KEYCODE_MAP[code];
    if (name && name.length > 0 && name !== '▽' && name !== '') return `KC_${name}`;
    return `(uint16_t)0x${code.toString(16).padStart(4, '0')}`;
  }
  if ((code & 0xFFF0) === 0x5220) return `MO(${code & 0xF})`;
  if ((code & 0xF000) === 0x4000) {
    const layer = (code >> 8) & 0xF;
    return `LT(${layer}, ${keycodeToC(code & 0xFF)})`;
  }
  if ((code & 0xFFF0) === 0x5230) return `TG(${code & 0xF})`;
  if (code >= 0x5200 && code <= 0x521F) return `TO(${code & 0x1F})`;
  if ((code & 0xFFF0) === 0x5260) return `OSL(${code & 0xF})`;
  if (code >= 0x6000 && code <= 0x7FFF && !(code >= 0x7700 && code <= 0x771F)) {
    const mod = (code >> 8) & 0x1F;
    const MOD_MAP = {
      0x01: 'MOD_LCTL', 0x02: 'MOD_LSFT', 0x04: 'MOD_LALT', 0x08: 'MOD_LGUI',
      0x11: 'MOD_RCTL', 0x12: 'MOD_RSFT', 0x14: 'MOD_RALT', 0x18: 'MOD_RGUI',
    };
    return `MT(${MOD_MAP[mod] ?? `0x${mod.toString(16)}`}, ${keycodeToC(code & 0xFF)})`;
  }
  return `(uint16_t)0x${code.toString(16).padStart(4, '0')}`;
}

function keyIdToEnum(id) {
  return `TD_${id.replace(/-/g, '_').toUpperCase()}`;
}

function buildTapDanceCCode(tapDanceKeys) {
  // Collect unique key IDs across all layers that have any config
  const keyIds = new Set();
  Object.values(tapDanceKeys).forEach(layerObj => {
    Object.entries(layerObj ?? {}).forEach(([keyId, e]) => {
      if (FIELDS.some(f => (e[f.key] ?? 0) !== 0)) keyIds.add(keyId);
    });
  });

  if (keyIds.size === 0) return '// No tap dance keys configured.';

  const stateMap = ['TD_SINGLE_TAP', 'TD_SINGLE_HOLD', 'TD_DOUBLE_TAP', 'TD_DOUBLE_HOLD'];
  const enumValues = [...keyIds].map(id => `    ${keyIdToEnum(id)}`).join(',\n');

  const callbacks = [...keyIds].map(id => {
    const enumId = keyIdToEnum(id);
    const fnBase = enumId.toLowerCase();
    const varName = `${fnBase}_state`;

    // Per-layer cases
    const layerCases = Object.entries(tapDanceKeys)
      .filter(([, layerObj]) => {
        const e = layerObj?.[id];
        return e && FIELDS.some(f => (e[f.key] ?? 0) !== 0);
      })
      .map(([layerIdx, layerObj]) => {
        const e = layerObj[id];
        const regLines = (reg) => FIELDS
          .map(({ key }, i) => (e[key] ?? 0) !== 0
            ? `                case ${stateMap[i]}: ${reg}(${keycodeToC(e[key])}); break;`
            : null)
          .filter(Boolean).join('\n');
        return `        case ${layerIdx}:\n            switch (${varName}.state) {\n${regLines('register_code16')}\n                default: break;\n            }\n            break;`;
      }).join('\n');

    const unregCases = Object.entries(tapDanceKeys)
      .filter(([, layerObj]) => {
        const e = layerObj?.[id];
        return e && FIELDS.some(f => (e[f.key] ?? 0) !== 0);
      })
      .map(([layerIdx, layerObj]) => {
        const e = layerObj[id];
        const regLines = (reg) => FIELDS
          .map(({ key }, i) => (e[key] ?? 0) !== 0
            ? `                case ${stateMap[i]}: ${reg}(${keycodeToC(e[key])}); break;`
            : null)
          .filter(Boolean).join('\n');
        return `        case ${layerIdx}:\n            switch (${varName}.state) {\n${regLines('unregister_code16')}\n                default: break;\n            }\n            break;`;
      }).join('\n');

    return `static td_tap_t ${varName} = {0};

void ${fnBase}_finished(tap_dance_state_t *state, void *user_data) {
    ${varName}.state = cur_dance(state);
    uint8_t layer = get_highest_layer(layer_state);
    switch (layer) {
${layerCases}
        default: break;
    }
}

void ${fnBase}_reset(tap_dance_state_t *state, void *user_data) {
    uint8_t layer = get_highest_layer(layer_state);
    switch (layer) {
${unregCases}
        default: break;
    }
    ${varName}.state = TD_NONE;
}`;
  }).join('\n\n');

  const actionsTable = [...keyIds]
    .map(id => {
      const enumId = keyIdToEnum(id);
      return `    [${enumId}] = ACTION_TAP_DANCE_FN_ADVANCED(NULL, ${enumId.toLowerCase()}_finished, ${enumId.toLowerCase()}_reset)`;
    }).join(',\n');

  return `// Generated by iris-key-editor — Tap Dance
// Paste into keymap.c. Use TD(ENUM_NAME) in your keymap layers.
// Ensure TAP_DANCE_ENABLE = yes in rules.mk.

#include QMK_KEYBOARD_H

typedef enum {
    TD_NONE, TD_SINGLE_TAP, TD_SINGLE_HOLD, TD_DOUBLE_TAP, TD_DOUBLE_HOLD
} td_state_t;

typedef struct { bool is_press_action; td_state_t state; } td_tap_t;

td_state_t cur_dance(tap_dance_state_t *state) {
    if (state->count == 1) {
        if (state->interrupted || !state->pressed) return TD_SINGLE_TAP;
        return TD_SINGLE_HOLD;
    }
    if (state->count == 2) {
        if (state->pressed) return TD_DOUBLE_HOLD;
        return TD_DOUBLE_TAP;
    }
    return TD_NONE;
}

enum {
${enumValues}
};

${callbacks}

tap_dance_action_t tap_dance_actions[] = {
${actionsTable}
};`;
}

function TdCodeModal({ code, onClose, copied, onCopy }) {
  return (
    <div className="td-modal-overlay" onClick={onClose}>
      <div className="td-modal" onClick={e => e.stopPropagation()}>
        <div className="td-modal-header">
          <span>Generated Tap Dance C Code</span>
          <div className="td-modal-btns">
            <button onClick={onCopy}>{copied ? '✓ Copied' : 'Copy'}</button>
            <button onClick={onClose}>Close</button>
          </div>
        </div>
        <pre className="td-modal-code">{code}</pre>
        <div className="td-modal-hint">
          Add to <code>keymap.c</code>. In keymap layers, use <code>TD(TD_LEFT_M_X_X)</code> for each key.
          Ensure <code>TAP_DANCE_ENABLE = yes</code> in <code>rules.mk</code>.
        </div>
      </div>
    </div>
  );
}

export default function TapDanceKeyPanel({ selectedKey, currentLayer, tapDanceKeys, onTapDanceKeysChange }) {
  const [activeTdField, setActiveTdField] = useState(null);
  const [pickerRequest, setPickerRequest]   = useState(null);
  const [showCodeModal, setShowCodeModal]   = useState(false);
  const [copied, setCopied]                 = useState(false);

  const keyObj = selectedKey
    ? [...HALVES.left, ...HALVES.right].find(
        k => k.viaRow === selectedKey.row && k.viaCol === selectedKey.col
      )
    : null;

  const layerKeys = tapDanceKeys[currentLayer] ?? {};
  const keyId  = keyObj?.id ?? null;
  const entry  = (keyId && layerKeys[keyId]) ?? { ...EMPTY_ENTRY };
  const hasAny = keyId && FIELDS.some(f => (entry[f.key] ?? 0) !== 0);

  // Count all configured keys across all layers
  const totalConfigured = Object.values(tapDanceKeys).reduce((sum, layerObj) =>
    sum + Object.values(layerObj).filter(e => FIELDS.some(f => (e[f.key] ?? 0) !== 0)).length, 0
  );

  const updateEntry = (field, code) => {
    if (!keyId) return;
    onTapDanceKeysChange(prev => ({
      ...prev,
      [currentLayer]: {
        ...(prev[currentLayer] ?? {}),
        [keyId]: { ...((prev[currentLayer] ?? {})[keyId] ?? EMPTY_ENTRY), [field]: code },
      },
    }));
  };

  const removeEntry = () => {
    if (!keyId) return;
    onTapDanceKeysChange(prev => {
      const layerCopy = { ...(prev[currentLayer] ?? {}) };
      delete layerCopy[keyId];
      return { ...prev, [currentLayer]: layerCopy };
    });
    setActiveTdField(null);
  };

  const handleFieldClick = (field) => {
    const newActive = activeTdField === field ? null : field;
    setActiveTdField(newActive);
    if (newActive) setPickerRequest({ code: entry[newActive] ?? 0 });
  };

  const handlePickerSelect = (code) => {
    if (activeTdField) updateEntry(activeTdField, code);
  };

  const codeContent = buildTapDanceCCode(tapDanceKeys);

  const copyCode = () => {
    navigator.clipboard.writeText(codeContent).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    });
  };

  return (
    <div className="td-panel">
      <div className="td-panel-header">
        <span className="td-panel-title">Tap Dance</span>
        {totalConfigured > 0 && (
          <span className="td-panel-count">{totalConfigured} key{totalConfigured !== 1 ? 's' : ''} configured</span>
        )}
      </div>

      {!keyObj ? (
        <div className="td-no-selection">
          <p>Click a key on the grid to configure its tap dance behavior.</p>
        </div>
      ) : (
        <>
          <div className="td-key-label">
            <span className="td-key-name">{keyObj.label}</span>
            <span className="td-key-id">{keyId}</span>
          </div>

          <div className="td-fields">
            {FIELDS.map(({ key, label }) => (
              <div
                key={key}
                className={`td-field-row${activeTdField === key ? ' active' : ''}`}
                onClick={() => handleFieldClick(key)}
              >
                <span className="td-field-label">{label}</span>
                <span className={`td-field-code${(entry[key] ?? 0) === 0 ? ' empty' : ''}`}>
                  {(entry[key] ?? 0) === 0
                    ? '—'
                    : (decodeQuantum(entry[key]) ?? `0x${entry[key].toString(16)}`)}
                </span>
              </div>
            ))}
          </div>

          <div className="td-term-row">
            <span className="td-term-label">Tapping Term</span>
            <input
              type="number"
              className="td-term-input"
              value={entry.tapping_term_ms ?? 0}
              min={0}
              max={2000}
              placeholder="0"
              onChange={e => updateEntry('tapping_term_ms', parseInt(e.target.value) || 0)}
            />
            <span className="td-term-unit">ms (0 = global)</span>
          </div>

          {hasAny && (
            <button className="td-remove-btn" onClick={removeEntry}>
              Remove TD from this key
            </button>
          )}

          {activeTdField && (
            <div className="td-picker-wrap">
              <div className="td-picker-hint">
                Selecting: <strong>{FIELDS.find(f => f.key === activeTdField)?.label}</strong>
                <button className="td-picker-close" onClick={() => setActiveTdField(null)}>✕</button>
              </div>
              <KeyPicker onSelect={handlePickerSelect} focusRequest={pickerRequest} />
            </div>
          )}
        </>
      )}

      <div className="td-actions">
        <button
          className="td-generate-btn"
          onClick={() => setShowCodeModal(true)}
          disabled={totalConfigured === 0}
        >
          Generate C Code
        </button>
      </div>

      {showCodeModal && (
        <TdCodeModal
          code={codeContent}
          onClose={() => setShowCodeModal(false)}
          copied={copied}
          onCopy={copyCode}
        />
      )}
    </div>
  );
}
