import { keycodeToC } from './keycodeToC';

// Compile-time macro slots, assigned via custom keycodes QK_USER_0..QK_USER_31
// (SAFE_RANGE = 0x7E40, confirmed free range with no firmware collisions).
export const EXTRA_MACRO_COUNT = 32;
export const EXTRA_MACRO_KEYCODE_BASE = 0x7E40;

export function extraMacroKeycode(n) {
  return EXTRA_MACRO_KEYCODE_BASE + n;
}

export function isExtraMacroKeycode(code) {
  return code >= EXTRA_MACRO_KEYCODE_BASE && code < EXTRA_MACRO_KEYCODE_BASE + EXTRA_MACRO_COUNT;
}

// SEND_STRING only safely supports printable ASCII plus newline/tab.
const SEND_STRING_SAFE_RE = /^[\x20-\x7E\n\t]*$/;

export function isSendStringSafe(value) {
  return SEND_STRING_SAFE_RE.test(value ?? '');
}

export function escapeSendString(value) {
  return (value ?? '')
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\t/g, '\\t')
    .replace(/[^\x20-\x7E]/g, '');
}

function actionToC(action) {
  switch (action.type) {
    case 'tap':
      return `tap_code16(${keycodeToC(action.keycode)});`;
    case 'down':
      return `register_code16(${keycodeToC(action.keycode)});`;
    case 'up':
      return `unregister_code16(${keycodeToC(action.keycode)});`;
    case 'delay':
      return `wait_ms(${Math.max(0, action.ms | 0)});`;
    case 'text':
      return `SEND_STRING("${escapeSendString(action.value)}");`;
    default:
      return '';
  }
}

// Generates extra_macros.c. Empty extraMacros produces the same output as
// the stub file checked into the keymap.
export function buildExtraMacroCCode(extraMacros) {
  const lines = [];
  lines.push('// Extra Macros — generated by Iris Key Editor.');
  lines.push('// Compile-time macro slots MU(0)-MU(31), assigned via custom keycodes');
  lines.push('// QK_USER_0..QK_USER_31 (0x7E40-0x7E5F). Edit in the Macros tab "Compile');
  lines.push('// Macros" section, then Generate C Code → Save to file.');

  const slots = (extraMacros ?? [])
    .map((actions, n) => ({ n, actions: actions ?? [] }))
    .filter(({ actions }) => actions.length > 0);

  if (slots.length === 0) {
    lines.push('// ** Stub: open Macros tab → Compile Macros → Generate C Code → Save to file **');
    lines.push('');
    lines.push('bool process_record_user(uint16_t keycode, keyrecord_t *record) {');
    lines.push('    return true;');
    lines.push('}');
    return lines.join('\n') + '\n';
  }

  lines.push('');
  lines.push('bool process_record_user(uint16_t keycode, keyrecord_t *record) {');
  lines.push('    switch (keycode) {');
  for (const { n, actions } of slots) {
    lines.push(`        case QK_USER_${n}:`);
    lines.push('            if (record->event.pressed) {');
    for (const action of actions) {
      const code = actionToC(action);
      if (code) lines.push(`                ${code}`);
    }
    lines.push('            }');
    lines.push('            return false;');
  }
  lines.push('        default:');
  lines.push('            return true;');
  lines.push('    }');
  lines.push('}');
  return lines.join('\n') + '\n';
}
